package com.java.moudle.system.domain;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.alibaba.fastjson.annotation.JSONField;
import com.java.until.dba.BaseDomain;

/**
 * 相关应用（预约挂号、健康信息、随访记录表、家庭医生签约、门诊信息、住院信息、检查报告、检验报告、双向转诊、已接种信息）(sys_application_list)
 * 
 * @author ljf
 * @version 1.0.0 2020-03-04
 */
@Entity
@Table(name = "sys_application_list")
public class SysApplicationList extends BaseDomain implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -7567334532428440174L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private String id;

    /** 服务URL */
    private String url;

    /** 服务名 */
    private String applicationName;

    /** 图片地址 */
    private String pictureAddress;

    /** 创建时间 */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /** 创建人 */
    private String createUser;
    
    /** 状态 */
    private String status;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取服务URL
     * 
     * @return 服务URL
     */
    public String getUrl() {
        return this.url;
    }

    /**
     * 设置服务URL
     * 
     * @param url
     *          服务URL
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * 获取服务名
     * 
     * @return 服务名
     */
    public String getApplicationName() {
        return this.applicationName;
    }

    /**
     * 设置服务名
     * 
     * @param applicationName
     *          服务名
     */
    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName;
    }

    /**
     * 获取图片地址
     * 
     * @return 图片地址
     */
    public String getPictureAddress() {
        return this.pictureAddress;
    }

    /**
     * 设置图片地址
     * 
     * @param pictureAddress
     *          图片地址
     */
    public void setPictureAddress(String pictureAddress) {
        this.pictureAddress = pictureAddress;
    }

    /**
     * 获取创建时间
     * 
     * @return 创建时间
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置创建时间
     * 
     * @param createTime
     *          创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取创建人
     * 
     * @return 创建人
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * 设置创建人
     * 
     * @param createUser
     *          创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

    /* This code was generated by TableGo tools, mark 2 end. */
}