package com.java.moudle.system.domain;


import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.java.until.dba.BaseDomain;

/**
 * 联系人客户关联表(sys_custormer_lnr)
 * 
 * @author tz
 * @version 1.0.0 2020-03-03
 */
@Entity
@Table(name = "sys_custormer_lnr")
public class SysCustormerLnr extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = 4809143842333320053L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 唯一标识 */
    @Id
    private String id;

    /** 客户id */
    private String custormerId; 

    /** 联系人id */
    private String lnrId;

    /** 与客户关系 1.本人 2.母亲 3.父亲 4.妻子 5.女儿 6.儿子 7.丈夫 8.其他*/
    private String gx;

    /** 关系其他*/
    private String gxOther;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    public String getGxOther() {
        return gxOther;
    }

    public void setGxOther(String gxOther) {
        this.gxOther = gxOther;
    }

    /**
     * 获取唯一标识
     * 
     * @return 唯一标识
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置唯一标识
     * 
     * @param id
     *          唯一标识
     */
    public void setId(String id) {
        this.id = id;
    }

 
    public String getCustormerId() {
		return custormerId;
	}

	public void setCustormerId(String custormerId) {
		this.custormerId = custormerId;
	}

	public String getLnrId() {
		return lnrId;
	}

	public void setLnrId(String lnrId) {
		this.lnrId = lnrId;
	}

	/**
     * 获取与客户关系
     * 
     * @return 与客户关系
     */
    public String getGx() {
        return this.gx;
    }

    /**
     * 设置与客户关系
     * 
     * @param gx
     *          与客户关系
     */
    public void setGx(String gx) {
        this.gx = gx;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}
