package com.java.moudle.system.domain;


import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.java.until.dba.BaseDomain;

/**
 * sys_dict
 * 
 * @author tz
 * @version 1.0.0 2020-03-03
 */
@Entity
@Table(name = "sys_dict")
public class SysDict extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = -6678426523348380290L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键 */
    @Id
    private String id;

    /** 上级标识 */
    private String parentId;

    /** code */
    private String code;

    /** 名称 */
    private String name;

    /** 更新人 */
    private String updateUser;

    /** 更新时间 */
    private Date updateTime;

    /** 备注 */
    private String remark;

    /** 删除 0.否 1.是 */
    private Integer deleteFlg;
    
    private String orderNum;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取主键
     * 
     * @return 主键
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置主键
     * 
     * @param id
     *          主键
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取上级标识
     * 
     * @return 上级标识
     */
    public String getParentId() {
        return this.parentId;
    }

    /**
     * 设置上级标识
     * 
     * @param parentId
     *          上级标识
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * 获取code
     * 
     * @return code
     */
    public String getCode() {
        return this.code;
    }

    /**
     * 设置code
     * 
     * @param code
     *          code
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * 获取名称
     * 
     * @return 名称
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置名称
     * 
     * @param name
     *          名称
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取更新人
     * 
     * @return 更新人
     */
    public String getUpdateUser() {
        return this.updateUser;
    }

    /**
     * 设置更新人
     * 
     * @param updateUser
     *          更新人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * 获取更新时间
     * 
     * @return 更新时间
     */
    public Date getUpdateTime() {
        return this.updateTime;
    }

    /**
     * 设置更新时间
     * 
     * @param updateTime
     *          更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 获取备注
     * 
     * @return 备注
     */
    public String getRemark() {
        return this.remark;
    }

    /**
     * 设置备注
     * 
     * @param remark
     *          备注
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * 获取删除 0.否 1.是
     * 
     * @return 删除 0
     */
    public Integer getDeleteFlg() {
        return this.deleteFlg;
    }

    /**
     * 设置删除 0.否 1.是
     * 
     * @param deleteFlg
     *          删除 0
     */
    public void setDeleteFlg(Integer deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

	public String getOrderNum() {
		return orderNum;
	}

	public void setOrderNum(String orderNum) {
		this.orderNum = orderNum;
	}

    /* This code was generated by TableGo tools, mark 2 end. */
}