package com.java.moudle.system.domain;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.springframework.web.multipart.MultipartFile;

import com.java.until.dba.BaseDomain;

/**
 * 办事指南类别表(sys_guide_category)
 * 
 * @author ljf
 * @version 1.0.0 2020-03-05
 */
@Entity
@Table(name = "sys_guide_category")
public class SysGuideCategory extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = -5307167765677259731L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键 */
    @Id
    private String id;

    /** 类别名称 */
    private String name;

    /** 封面地址 */
    private String imageUrl;

    /** 排序 */
    private String orderNum;

    /** 状态 (0.正常 1.删除)  */
    private String status;

    @Transient
    private MultipartFile imageFile;
    @Transient
    private String guideNum;
    @Transient
    private String xh;
    
    
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public String getOrderNum() {
		return orderNum;
	}

	public void setOrderNum(String orderNum) {
		this.orderNum = orderNum;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public MultipartFile getImageFile() {
		return imageFile;
	}

	public void setImageFile(MultipartFile imageFile) {
		this.imageFile = imageFile;
	}

	public String getGuideNum() {
		return guideNum;
	}

	public void setGuideNum(String guideNum) {
		this.guideNum = guideNum;
	}

	public String getXh() {
		return xh;
	}

	public void setXh(String xh) {
		this.xh = xh;
	}

}