package com.java.moudle.system.domain;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.alibaba.fastjson.annotation.JSONField;
import com.java.until.dba.BaseDomain;

/**
 * sys_guide_inspect
 * 
 * @author ljf
 * @version 1.0.0 2020-03-05
 */
@Entity
@Table(name = "sys_guide_inspect")
public class SysGuideInspect extends BaseDomain implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -2087334491440001483L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private String id;

    /** guideType */
    private String guideType;
    
    /**
     * guideType中文
     */
    @Transient
    private String guideTypeName;
    
    /**
     * guideType图片
     */
    @Transient
    private String imageUrl;

    /** title */
    private String title;

    /** content */
    private String content;

    /** 状态 (0.未提交 1.提交-审核中 2.审核通过 5.退回 6.撤回)  */
    private String status;

    /** 创建时间 */
    @Column(updatable = false)
    @JSONField(format="yyyy-MM-dd")
    private Date createTime;

    /** 创建人 */
    @Column(updatable = false)
    private String createUser;
    
    /** 封面url */
    private String guideUrl;
    
    /** 发表时间 */
    @JSONField(format="yyyy-MM-dd")
    private Date pubTime;
    
    private String deleteFlg;//删除标识（0：正常 1.删除）
    
    // 查询开始时间
    @Transient
    private String startTime;
    
    // 查询结束时间
    @Transient
    private String endTime;
    
    // 退回原因
    private String remarks;
    
    @Transient
    private String roleType; //1.超级管理员 2.管理员 3.普通用户
    @Transient
    private List<String> userIds;//用户标识集合
    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取guideType
     * 
     * @return guideType
     */
    public String getGuideType() {
        return this.guideType;
    }

    /**
     * 设置guideType
     * 
     * @param guideType
     */
    public void setGuideType(String guideType) {
        this.guideType = guideType;
    }

    public String getGuideTypeName() {
		return guideTypeName;
	}

	public void setGuideTypeName(String guideTypeName) {
		this.guideTypeName = guideTypeName;
	}

	/**
     * 获取title
     * 
     * @return title
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * 设置title
     * 
     * @param title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	/**
     * 获取status
     * 
     * @return status
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * 设置status
     * 
     * @param status
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * 获取createTime
     * 
     * @return createTime
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置createTime
     * 
     * @param createTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	public String getCreateUser() {
		return createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public String getGuideUrl() {
		return guideUrl;
	}

	public void setGuideUrl(String guideUrl) {
		this.guideUrl = guideUrl;
	}

	public Date getPubTime() {
		return pubTime;
	}

	public void setPubTime(Date pubTime) {
		this.pubTime = pubTime;
	}

	public String getDeleteFlg() {
		return deleteFlg;
	}

	public void setDeleteFlg(String deleteFlg) {
		this.deleteFlg = deleteFlg;
	}

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getRoleType() {
		return roleType;
	}

	public void setRoleType(String roleType) {
		this.roleType = roleType;
	}

	public List<String> getUserIds() {
		return userIds;
	}

	public void setUserIds(List<String> userIds) {
		this.userIds = userIds;
	}

    /* This code was generated by TableGo tools, mark 2 end. */
}