package com.java.moudle.system.domain;


import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.java.until.dba.BaseDomain;

/**
 * 联系人文件表(sys_lnr_file)
 * 
 * @author tz
 * @version 1.0.0 2020-03-03
 */
@Entity
@Table(name = "sys_lnr_file")
public class SysLnrFile extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = -8086021911818915279L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 唯一标示 */
    @Id
    private String id;

    /** 联系人ID */
    private String lnrId;

    /** 身份证正面地址 */
    private String sfzhzmUrl;

    /** 身份证反面地址 */
    private String sfzhfmUrl;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取唯一标示
     * 
     * @return 唯一标示
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置唯一标示
     * 
     * @param id
     *          唯一标示
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取联系人ID
     * 
     * @return 联系人ID
     */
    public String getLnrId() {
        return this.lnrId;
    }

    /**
     * 设置联系人ID
     * 
     * @param lnrId
     *          联系人ID
     */
    public void setLnrId(String lnrId) {
        this.lnrId = lnrId;
    }

    /**
     * 获取身份证正面地址
     * 
     * @return 身份证正面地址
     */
    public String getSfzhzmUrl() {
        return this.sfzhzmUrl;
    }

    /**
     * 设置身份证正面地址
     * 
     * @param sfzhzmUrl
     *          身份证正面地址
     */
    public void setSfzhzmUrl(String sfzhzmUrl) {
        this.sfzhzmUrl = sfzhzmUrl;
    }

    /**
     * 获取身份证反面地址
     * 
     * @return 身份证反面地址
     */
    public String getSfzhfmUrl() {
        return this.sfzhfmUrl;
    }

    /**
     * 设置身份证反面地址
     * 
     * @param sfzhfmUrl
     *          身份证反面地址
     */
    public void setSfzhfmUrl(String sfzhfmUrl) {
        this.sfzhfmUrl = sfzhfmUrl;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}