package com.java.moudle.system.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.alibaba.fastjson.annotation.JSONField;
import com.java.until.StringUntil;
import com.java.until.dba.BaseDomain;

/**
 * 健康咨讯(news_health)
 * 
 * @author tz
 * @version 1.0.0 2020-03-03
 */
@Entity
@Table(name = "news_health")
public class SysNewsHealth extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = -1605615601540885370L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 唯一标示 */
    @Id
    private String id;

    /** 咨讯标题 */
    private String newsTitle;

    /** 咨讯来源 */
    private String newsLy;
    
    /** 咨讯来源说明 */
    private String newsLyDesc;

    /** 咨讯类别标识 */
    private String newsCatId;

    /** 咨讯封面地址 */
    private String newsUrl;

    /** 咨讯内容 */
    private String newsContent;

    /** 咨讯状态(0.未提交 1.退回 2.撤回 3.提交-审核中 4.审核通过 5.发表 6.置顶)*/
    private String status;

    /** 创建时间 */
    @Column(updatable = false)
    @JSONField(format="yyyy-MM-dd")
    private Date createTime;
    
    /** 创建人 */
    @Column(updatable = false)
    private String createUser;
    
    /** 发布时间 */
    @JSONField(format="yyyy-MM-dd")
    private Date pubTime;
    
    @Transient
    private String newsCatName;
    @Transient
    private String subTitle;
    
    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取唯一标示
     * 
     * @return 唯一标示
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置唯一标示
     * 
     * @param id
     *          唯一标示
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取咨讯标题
     * 
     * @return 咨讯标题
     */
    public String getNewsTitle() {
        return this.newsTitle;
    }

    /**
     * 设置咨讯标题
     * 
     * @param newsTitle
     *          咨讯标题
     */
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle;
    }

    /**
     * 获取咨讯来源
     * 
     * @return 咨讯来源
     */
    public String getNewsLy() {
        return this.newsLy;
    }

    /**
     * 设置咨讯来源
     * 
     * @param newsLy
     *          咨讯来源
     */
    public void setNewsLy(String newsLy) {
        this.newsLy = newsLy;
    }

    public String getNewsLyDesc() {
		return newsLyDesc;
	}

	public void setNewsLyDesc(String newsLyDesc) {
		this.newsLyDesc = newsLyDesc;
	}

	public String getNewsCatId() {
		return newsCatId;
	}

	public void setNewsCatId(String newsCatId) {
		this.newsCatId = newsCatId;
	}

	/**
     * 获取咨讯封面地址
     * 
     * @return 咨讯封面地址
     */
    public String getNewsUrl() {
        return this.newsUrl;
    }

    /**
     * 设置咨讯封面地址
     * 
     * @param newsUrl
     *          咨讯封面地址
     */
    public void setNewsUrl(String newsUrl) {
        this.newsUrl = newsUrl;
    }

    /**
     * 获取咨讯内容
     * 
     * @return 咨讯内容
     */
    public String getNewsContent() {
        return this.newsContent;
    }

    /**
     * 设置咨讯内容
     * 
     * @param newsContent
     *          咨讯内容
     */
    public void setNewsContent(String newsContent) {
    	if(StringUntil.isNotBlank(newsContent)) {
    		String reg = "[^\u4e00-\u9fa5]";
    		String temp = newsContent.replaceAll(reg, "");
			this.subTitle = temp.substring(0, (temp.length() > 60) ? 60 : temp.length());
    	}
    	
        this.newsContent = newsContent;
    }

    /**
     * 获取咨讯状态
     * 
     * @return 咨讯状态
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * 设置咨讯状态
     * 
     * @param status
     *          咨讯状态
     */
    public void setStatus(String status) {
        this.status = status;
    }

	public String getNewsCatName() {
		return newsCatName;
	}

	public void setNewsCatName(String newsCatName) {
		this.newsCatName = newsCatName;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCreateUser() {
		return createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getPubTime() {
		return pubTime;
	}

	public void setPubTime(Date pubTime) {
		this.pubTime = pubTime;
	}

	public String getSubTitle() {
		return subTitle;
	}

	public void setSubTitle(String subTitle) {
		this.subTitle = subTitle;
	}

    /* This code was generated by TableGo tools, mark 2 end. */
}