package com.java.moudle.system.domain;


import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.java.until.dba.BaseDomain;

/**
 * 健康咨询类别(news_category)
 * 
 * @author tz
 * @version 1.0.0 2020-03-03
 */
@Entity
@Table(name = "news_category")
public class SysNewsCategory extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = 5958233912760649209L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 唯一标识 */
    @Id
    private String id;

    /** 类别名称 */
    private String name;

    /** 序号 */
    private Integer orderNum;

    /** 状态 0：正常 1：删除 */
    private String status;

    @Transient
    private String newsHealthNum;
    @Transient
    private String xh;
    @Transient
    private Integer oldOrderNum;
    
    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取唯一标识
     * 
     * @return 唯一标识
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置唯一标识
     * 
     * @param id
     *          唯一标识
     */
    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

    public Integer getOrderNum() {
		return orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	/**
     * 获取状态
     * 
     * @return 状态
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * 设置状态
     * 
     * @param status
     *          状态
     */
    public void setStatus(String status) {
        this.status = status;
    }

	public String getNewsHealthNum() {
		return newsHealthNum;
	}

	public void setNewsHealthNum(String newsHealthNum) {
		this.newsHealthNum = newsHealthNum;
	}

	public String getXh() {
		return xh;
	}

	public void setXh(String xh) {
		this.xh = xh;
	}

	public Integer getOldOrderNum() {
		return oldOrderNum;
	}

	public void setOldOrderNum(Integer oldOrderNum) {
		this.oldOrderNum = oldOrderNum;
	}


    /* This code was generated by TableGo tools, mark 2 end. */
}