package com.java.moudle.physicalExamination.domain;

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.java.until.dba.BaseDomain;

/**
 * blt_tj_info
 * 
 * @author ljf
 * @version 1.0.0 2020-03-18
 */
@Entity
@Table(name = "blt_tj_info")
public class BltTjInfo extends BaseDomain implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -4633842818595167541L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private String id;
    
    /** 人群类型 */
    private String rqlxCode;

    /** 修改人 */
    private String updateUser;

    /** 修改时间 */
    private Date updateTime;

    /** 所属机构 */
    private String orgName;

    /** 指导信息 */
    private String guideInfo;
    
    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.DETACH, mappedBy = "tjInfoId")
    @NotFound(action = NotFoundAction.IGNORE)
    private List<BltTjData> tjData;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取人群类型
     * 
     * @return 人群类型
     */
    public String getRqlxCode() {
        return this.rqlxCode;
    }

    /**
     * 设置人群类型
     * 
     * @param rqlxCode
     *          人群类型
     */
    public void setRqlxCode(String rqlxCode) {
        this.rqlxCode = rqlxCode;
    }

	/**
     * 获取修改人
     * 
     * @return 修改人
     */
    public String getUpdateUser() {
        return this.updateUser;
    }

    /**
     * 设置修改人
     * 
     * @param updateUser
     *          修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * 获取修改时间
     * 
     * @return 修改时间
     */
    public Date getUpdateTime() {
        return this.updateTime;
    }

    /**
     * 设置修改时间
     * 
     * @param updateTime
     *          修改时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }


    /**
     * 获取指导信息
     * 
     * @return 指导信息
     */
    public String getGuideInfo() {
        return this.guideInfo;
    }

    /**
     * 设置指导信息
     * 
     * @param guideInfo
     *          指导信息
     */
    public void setGuideInfo(String guideInfo) {
        this.guideInfo = guideInfo;
    }

	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public List<BltTjData> getTjData() {
		return tjData;
	}

	public void setTjData(List<BltTjData> tjData) {
		this.tjData = tjData;
	}

    /* This code was generated by TableGo tools, mark 2 end. */
}