package com.java.moudle.bphs.archive.dto;


public class BlsDto {


    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private String id;

    /** 字典值 */
    private String code;

    /** 描述 */
    private String depict;

    /** 居民id */
    private String jmid;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取字典值
     * 
     * @return 字典值
     */
    public String getCode() {
//    	String code = DictUntils.getDictValue(InstanceFactory.getInstance(CacheParentCode.class).getExposureHistoryType(), this.code);
        if (code != null) {
        	return code;
        } else {
        	return this.code;
        }
    }

    /**
     * 设置字典值
     * 
     * @param code
     *          字典值
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * 获取描述
     * 
     * @return 描述
     */
    public String getDepict() {
        return this.depict;
    }

    /**
     * 设置描述
     * 
     * @param depict
     *          描述
     */
    public void setDepict(String depict) {
        this.depict = depict;
    }

    /**
     * 获取居民id
     * 
     * @return 居民id
     */
    public String getJmid() {
        return this.jmid;
    }

    /**
     * 设置居民id
     * 
     * @param jmid
     *          居民id
     */
    public void setJmid(String jmid) {
        this.jmid = jmid;
    }

    /* This code was generated by TableGo tools, mark 2 end. */

}
