package com.java.moudle.tripartdock.help.admin;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.java.until.dba.BaseDomain;

/**
 * 常见问题表(blt_common_problem)
 * 
 * @author ljf
 * @version 1.0.0 2019-12-17
 */
@Entity
@Table(name = "blt_common_problem")
public class BltCommonProblem extends BaseDomain implements java.io.Serializable {
	private static final long serialVersionUID = -7849714709919715323L;

    /** id */
    @Id
    private String id;

    /** 问题分类1：APP使用  2：测量设备 */
    private Integer wtfl;

    /** 问题 */
    private String problem;

    /** 回答 */
    private String answer;

    /** 1 正常   3 删除 */
    private Integer status;

    /** 创建人ID */
    private String createUser;

    /** 创建时间 */
    @JsonFormat(pattern="yyyy-MM-dd HH:MM:SS",timezone="GMT+8")
    private Date createTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取问题分类1：APP使用  2：测量设备
     * 
     * @return 问题分类1
     */
    public Integer getWtfl() {
        return this.wtfl;
    }

    /**
     * 设置问题分类1：APP使用  2：测量设备
     * 
     * @param wtfl
     *          问题分类1
     */
    public void setWtfl(Integer wtfl) {
        this.wtfl = wtfl;
    }

    /**
     * 获取问题
     * 
     * @return 问题
     */
    public String getProblem() {
        return this.problem;
    }

    /**
     * 设置问题
     * 
     * @param problem
     *          问题
     */
    public void setProblem(String problem) {
        this.problem = problem;
    }

    /**
     * 获取回答
     * 
     * @return 回答
     */
    public String getAnswer() {
        return this.answer;
    }

    /**
     * 设置回答
     * 
     * @param answer
     *          回答
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * 获取1 正常   3 删除
     * 
     * @return 1 正常   3 删除
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * 设置1 正常   3 删除
     * 
     * @param status
     *          1 正常   3 删除
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取创建人ID
     * 
     * @return 创建人ID
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * 设置创建人ID
     * 
     * @param createUser
     *          创建人ID
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * 获取创建时间
     * 
     * @return 创建时间
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置创建时间
     * 
     * @param createTime
     *          创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}
